pipeline { 
    agent any  
    stages { 
        stage('Build') { 

            steps {
            
               sh 'cd demo ls -al /usr/share/maven/bin/mvn install'


            }
        }
    
	}
}