pipeline { 
    agent any  
    stages { 
        stage('Build') { 
            steps { 

			   sh 'cd demo'
			   sh 'ls -al'
               sh '/usr/share/maven/bin/mvn install'




            }
        }
    
	}
}